name: Run Tests

# Trigger the workflow on pushes to the main and master branch and pull requests
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

# Define the jobs for the workflow
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up JDK 11 (or whichever version you are using)
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'adopt'

      # Step 3: Cache Maven dependencies to speed up the build process
      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Build the project using Maven
      - name: Build with Maven
        run: mvn clean install

      # Step 5: Run unit tests
      - name: Run unit tests
        run: mvn test